# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from marzapi.api.subscription_api import SubscriptionApi  # noqa: E501


class TestSubscriptionApi(unittest.TestCase):
    """SubscriptionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubscriptionApi()

    def tearDown(self) -> None:
        pass

    def test_user_get_usage(self) -> None:
        """Test case for user_get_usage

        User Get Usage  # noqa: E501
        """
        pass

    def test_user_subscription(self) -> None:
        """Test case for user_subscription

        User Subscription  # noqa: E501
        """
        pass

    def test_user_subscription_info(self) -> None:
        """Test case for user_subscription_info

        User Subscription Info  # noqa: E501
        """
        pass

    def test_user_subscription_with_client_type(self) -> None:
        """Test case for user_subscription_with_client_type

        User Subscription With Client Type  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
