# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from marzapi.models.user_template_response import UserTemplateResponse  # noqa: E501

class TestUserTemplateResponse(unittest.TestCase):
    """UserTemplateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserTemplateResponse:
        """Test UserTemplateResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserTemplateResponse`
        """
        model = UserTemplateResponse()  # noqa: E501
        if include_optional:
            return UserTemplateResponse(
                name = '',
                data_limit = 0.0,
                expire_duration = 0.0,
                username_prefix = '0',
                username_suffix = '0',
                inbounds = {
                    'key' : [
                        ''
                        ]
                    },
                id = 56
            )
        else:
            return UserTemplateResponse(
                id = 56,
        )
        """

    def testUserTemplateResponse(self):
        """Test UserTemplateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
