# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from marzapi.api.admin_api import AdminApi  # noqa: E501


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminApi()

    def tearDown(self) -> None:
        pass

    def test_admin_token(self) -> None:
        """Test case for admin_token

        Admin Token  # noqa: E501
        """
        pass

    def test_create_admin(self) -> None:
        """Test case for create_admin

        Create Admin  # noqa: E501
        """
        pass

    def test_get_admins(self) -> None:
        """Test case for get_admins

        Get Admins  # noqa: E501
        """
        pass

    def test_get_current_admin(self) -> None:
        """Test case for get_current_admin

        Get Current Admin  # noqa: E501
        """
        pass

    def test_modify_admin(self) -> None:
        """Test case for modify_admin

        Modify Admin  # noqa: E501
        """
        pass

    def test_remove_admin(self) -> None:
        """Test case for remove_admin

        Remove Admin  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
