# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from marzapi.api.user_template_api import UserTemplateApi  # noqa: E501


class TestUserTemplateApi(unittest.TestCase):
    """UserTemplateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserTemplateApi()

    def tearDown(self) -> None:
        pass

    def test_add_user_template(self) -> None:
        """Test case for add_user_template

        Add User Template  # noqa: E501
        """
        pass

    def test_get_user_template_endpoint(self) -> None:
        """Test case for get_user_template_endpoint

        Get User Template Endpoint  # noqa: E501
        """
        pass

    def test_get_user_templates(self) -> None:
        """Test case for get_user_templates

        Get User Templates  # noqa: E501
        """
        pass

    def test_modify_user_template(self) -> None:
        """Test case for modify_user_template

        Modify User Template  # noqa: E501
        """
        pass

    def test_remove_user_template(self) -> None:
        """Test case for remove_user_template

        Remove User Template  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
