# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from marzapi.api.core_api import CoreApi  # noqa: E501


class TestCoreApi(unittest.TestCase):
    """CoreApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CoreApi()

    def tearDown(self) -> None:
        pass

    def test_get_core_config(self) -> None:
        """Test case for get_core_config

        Get Core Config  # noqa: E501
        """
        pass

    def test_get_core_stats(self) -> None:
        """Test case for get_core_stats

        Get Core Stats  # noqa: E501
        """
        pass

    def test_modify_core_config(self) -> None:
        """Test case for modify_core_config

        Modify Core Config  # noqa: E501
        """
        pass

    def test_restart_core(self) -> None:
        """Test case for restart_core

        Restart Core  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
