# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from marzapi.models.user_usage_response import UserUsageResponse  # noqa: E501

class TestUserUsageResponse(unittest.TestCase):
    """UserUsageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserUsageResponse:
        """Test UserUsageResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserUsageResponse`
        """
        model = UserUsageResponse()  # noqa: E501
        if include_optional:
            return UserUsageResponse(
                node_id = 56,
                node_name = '',
                used_traffic = 56
            )
        else:
            return UserUsageResponse(
                node_name = '',
                used_traffic = 56,
        )
        """

    def testUserUsageResponse(self):
        """Test UserUsageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
