# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from marzapi.api.system_api import SystemApi  # noqa: E501


class TestSystemApi(unittest.TestCase):
    """SystemApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SystemApi()

    def tearDown(self) -> None:
        pass

    def test_get_hosts(self) -> None:
        """Test case for get_hosts

        Get Hosts  # noqa: E501
        """
        pass

    def test_get_inbounds(self) -> None:
        """Test case for get_inbounds

        Get Inbounds  # noqa: E501
        """
        pass

    def test_get_system_stats(self) -> None:
        """Test case for get_system_stats

        Get System Stats  # noqa: E501
        """
        pass

    def test_modify_hosts(self) -> None:
        """Test case for modify_hosts

        Modify Hosts  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
