# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from marzapi.models.proxy_host_security import ProxyHostSecurity  # noqa: E501

class TestProxyHostSecurity(unittest.TestCase):
    """ProxyHostSecurity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProxyHostSecurity(self):
        """Test ProxyHostSecurity"""
        # inst = ProxyHostSecurity()

if __name__ == '__main__':
    unittest.main()
