# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from marzapi.api.node_api import NodeApi  # noqa: E501


class TestNodeApi(unittest.TestCase):
    """NodeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NodeApi()

    def tearDown(self) -> None:
        pass

    def test_add_node(self) -> None:
        """Test case for add_node

        Add Node  # noqa: E501
        """
        pass

    def test_get_node(self) -> None:
        """Test case for get_node

        Get Node  # noqa: E501
        """
        pass

    def test_get_node_settings(self) -> None:
        """Test case for get_node_settings

        Get Node Settings  # noqa: E501
        """
        pass

    def test_get_nodes(self) -> None:
        """Test case for get_nodes

        Get Nodes  # noqa: E501
        """
        pass

    def test_get_usage(self) -> None:
        """Test case for get_usage

        Get Usage  # noqa: E501
        """
        pass

    def test_modify_node(self) -> None:
        """Test case for modify_node

        Modify Node  # noqa: E501
        """
        pass

    def test_reconnect_node(self) -> None:
        """Test case for reconnect_node

        Reconnect Node  # noqa: E501
        """
        pass

    def test_remove_node(self) -> None:
        """Test case for remove_node

        Remove Node  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
