# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from marzapi.api.user_api import UserApi  # noqa: E501


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_add_user(self) -> None:
        """Test case for add_user

        Add User  # noqa: E501
        """
        pass

    def test_delete_expired_users(self) -> None:
        """Test case for delete_expired_users

        Delete Expired Users  # noqa: E501
        """
        pass

    def test_get_expired_users(self) -> None:
        """Test case for get_expired_users

        Get Expired Users  # noqa: E501
        """
        pass

    def test_get_user(self) -> None:
        """Test case for get_user

        Get User  # noqa: E501
        """
        pass

    def test_get_user_usage(self) -> None:
        """Test case for get_user_usage

        Get User Usage  # noqa: E501
        """
        pass

    def test_get_users(self) -> None:
        """Test case for get_users

        Get Users  # noqa: E501
        """
        pass

    def test_get_users_usage(self) -> None:
        """Test case for get_users_usage

        Get Users Usage  # noqa: E501
        """
        pass

    def test_modify_user(self) -> None:
        """Test case for modify_user

        Modify User  # noqa: E501
        """
        pass

    def test_remove_user(self) -> None:
        """Test case for remove_user

        Remove User  # noqa: E501
        """
        pass

    def test_reset_user_data_usage(self) -> None:
        """Test case for reset_user_data_usage

        Reset User Data Usage  # noqa: E501
        """
        pass

    def test_reset_users_data_usage(self) -> None:
        """Test case for reset_users_data_usage

        Reset Users Data Usage  # noqa: E501
        """
        pass

    def test_revoke_user_subscription(self) -> None:
        """Test case for revoke_user_subscription

        Revoke User Subscription  # noqa: E501
        """
        pass

    def test_set_owner(self) -> None:
        """Test case for set_owner

        Set Owner  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
