# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from marzapi.models.node_response import NodeResponse  # noqa: E501

class TestNodeResponse(unittest.TestCase):
    """NodeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NodeResponse:
        """Test NodeResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NodeResponse`
        """
        model = NodeResponse()  # noqa: E501
        if include_optional:
            return NodeResponse(
                name = '',
                address = '',
                port = 56,
                api_port = 56,
                usage_coefficient = 1.337,
                id = 56,
                xray_version = '',
                status = 'connected',
                message = ''
            )
        else:
            return NodeResponse(
                name = '',
                address = '',
                id = 56,
                status = 'connected',
        )
        """

    def testNodeResponse(self):
        """Test NodeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
