# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from marzapi.models.user_data_limit_reset_strategy import UserDataLimitResetStrategy  # noqa: E501

class TestUserDataLimitResetStrategy(unittest.TestCase):
    """UserDataLimitResetStrategy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserDataLimitResetStrategy(self):
        """Test UserDataLimitResetStrategy"""
        # inst = UserDataLimitResetStrategy()

if __name__ == '__main__':
    unittest.main()
