# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from marzapi.models.user_status_modify import UserStatusModify  # noqa: E501

class TestUserStatusModify(unittest.TestCase):
    """UserStatusModify unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserStatusModify(self):
        """Test UserStatusModify"""
        # inst = UserStatusModify()

if __name__ == '__main__':
    unittest.main()
