# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from marzapi.models.user_status_create import UserStatusCreate  # noqa: E501

class TestUserStatusCreate(unittest.TestCase):
    """UserStatusCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserStatusCreate(self):
        """Test UserStatusCreate"""
        # inst = UserStatusCreate()

if __name__ == '__main__':
    unittest.main()
