# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ProxyHostALPN(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    EMPTY = ''
    H3 = 'h3'
    H2 = 'h2'
    HTTP_SLASH_1_DOT_1 = 'http/1.1'
    H3_COMMA_H2_COMMA_HTTP_SLASH_1_DOT_1 = 'h3,h2,http/1.1'
    H3_COMMA_H2 = 'h3,h2'
    H2_COMMA_HTTP_SLASH_1_DOT_1 = 'h2,http/1.1'

    @classmethod
    def from_json(cls, json_str: str) -> ProxyHostALPN:
        """Create an instance of ProxyHostALPN from a JSON string"""
        return ProxyHostALPN(json.loads(json_str))


