# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ProxyHostFingerprint(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    EMPTY = ''
    CHROME = 'chrome'
    FIREFOX = 'firefox'
    SAFARI = 'safari'
    IOS = 'ios'
    ANDROID = 'android'
    EDGE = 'edge'
    ENUM_360 = '360'
    QQ = 'qq'
    RANDOM = 'random'
    RANDOMIZED = 'randomized'

    @classmethod
    def from_json(cls, json_str: str) -> ProxyHostFingerprint:
        """Create an instance of ProxyHostFingerprint from a JSON string"""
        return ProxyHostFingerprint(json.loads(json_str))


