# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class UserDataLimitResetStrategy(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    NO_RESET = 'no_reset'
    DAY = 'day'
    WEEK = 'week'
    MONTH = 'month'
    YEAR = 'year'

    @classmethod
    def from_json(cls, json_str: str) -> UserDataLimitResetStrategy:
        """Create an instance of UserDataLimitResetStrategy from a JSON string"""
        return UserDataLimitResetStrategy(json.loads(json_str))


