# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, StrictInt, conlist
from marzapi.models.user_response import UserResponse

class UsersResponse(BaseModel):
    """
    UsersResponse
    """
    users: conlist(UserResponse) = Field(...)
    total: StrictInt = Field(...)
    __properties = ["users", "total"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UsersResponse:
        """Create an instance of UsersResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in users (list)
        _items = []
        if self.users:
            for _item in self.users:
                if _item:
                    _items.append(_item.to_dict())
            _dict['users'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UsersResponse:
        """Create an instance of UsersResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UsersResponse.parse_obj(obj)

        _obj = UsersResponse.parse_obj({
            "users": [UserResponse.from_dict(_item) for _item in obj.get("users")] if obj.get("users") is not None else None,
            "total": obj.get("total")
        })
        return _obj


