# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class UserStatus(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    ACTIVE = 'active'
    DISABLED = 'disabled'
    LIMITED = 'limited'
    EXPIRED = 'expired'
    ON_HOLD = 'on_hold'

    @classmethod
    def from_json(cls, json_str: str) -> UserStatus:
        """Create an instance of UserStatus from a JSON string"""
        return UserStatus(json.loads(json_str))


